#!/bin/bash

# 🇷🇸 Belgrade OS - Universal Setup Script
# Works on macOS (brew) and Linux (apt)

set -e

echo "🇷🇸 Belgrade OS Setup starting..."

# --- 1. OS Detection ---
OS="$(uname)"
case "${OS}" in
    Darwin*)    PACKAGE_MANAGER="brew";;
    Linux*)     PACKAGE_MANAGER="apt";;
    *)          echo "❌ Unsupported OS: ${OS}"; exit 1;;
esac

echo "Detected OS: ${OS} (Using ${PACKAGE_MANAGER})"

# --- 2. System Dependency Check ---
check_binary() {
    if ! command -v "$1" &> /dev/null; then
        echo "⚠️  $1 is not installed."
        return 1
    fi
    echo "✅ $1 is installed."
    return 0
}

install_system_deps() {
    if [ "${PACKAGE_MANAGER}" == "brew" ]; then
        brew install protobuf go rust python3 docker docker-compose
    else
        sudo apt-get update
        # Attempt to install common deps, but handle docker separately to avoid conflicts
        sudo apt-get install -y protobuf-compiler golang-go rustc cargo python3 python3-venv python3-pip libpq-dev build-essential

        if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt-get install -y docker.io docker-compose || {
                echo "⚠️  Standard Docker install failed. Attempting conflict resolution..."
                sudo apt-get remove -y containerd
                sudo apt-get install -y docker.io docker-compose
            }
        fi
    fi
}

# --- .env Generation ---
generate_env() {
    if [ -f ".env" ]; then
        echo "✅ .env already exists — skipping generation."
        return
    fi

    if ! command -v openssl &> /dev/null; then
        echo "⚠️  openssl not found — cannot generate random secrets. Edit .env manually."
        cp .env.example .env 2>/dev/null || true
        return
    fi

    echo "Generating .env with random secrets..."
    # Note: heredoc delimiter is intentionally unquoted — $(openssl rand -hex 32)
    # must be expanded by the shell to generate secrets.
    cat > .env << EOF
# Belgrade OS — auto-generated by setup.sh
# Fill in CF_TUNNEL_TOKEN from the Cloudflare dashboard before starting.
CF_TUNNEL_TOKEN=

DB_USER=laurent
DB_PASSWORD=$(openssl rand -hex 32)
REDIS_PASSWORD=$(openssl rand -hex 32)
CONTROLLER_API_TOKEN=$(openssl rand -hex 32)

# Service discovery — override when services run in containers (use container names)
BEG_OS_BRIDGE_URL=http://localhost:8081
BRIDGE_URL=http://localhost:8081
BEG_OS_DB_URL=postgresql+asyncpg://laurent:\${DB_PASSWORD}@localhost:5432/belgrade_os
EOF
    chmod 600 .env
    echo "✅ .env created. Fill in CF_TUNNEL_TOKEN then run: make start"
}

# --- Redis ACL Generation ---
generate_acl() {
    if [ -f "config/redis.acl" ]; then
        echo "✅ config/redis.acl already exists — skipping generation."
        return
    fi

    if ! command -v openssl &> /dev/null; then
        echo "⚠️  openssl not found — copy config/redis.acl.template to config/redis.acl and fill in passwords manually."
        return
    fi

    echo "Generating config/redis.acl with per-service passwords..."
    mkdir -p config

    GATEWAY_PASS=$(openssl rand -hex 32)
    INFERENCE_PASS=$(openssl rand -hex 32)
    RUNNER_PASS=$(openssl rand -hex 32)
    NOTIFICATION_PASS=$(openssl rand -hex 32)
    VAULT_PASS=$(openssl rand -hex 32)
    BRIDGE_PASS=$(openssl rand -hex 32)
    CONTROLLER_PASS=$(openssl rand -hex 32)
    APP_PASS=$(openssl rand -hex 32)

    cat > config/redis.acl << EOF
user default off nopass nocommands
user gateway on >${GATEWAY_PASS} ~perms:* ~tasks:inbound &sse:* +ping +hget +hmget +xadd +subscribe
user inference on >${INFERENCE_PASS} ~tasks:* &sse:* +ping +xreadgroup +xread +xadd +xack +xgroup +publish
user runner on >${RUNNER_PASS} ~tasks:tool_calls ~tasks:tool_results ~lease:* +ping +xreadgroup +xadd +xack +xgroup +set +del
user notification on >${NOTIFICATION_PASS} ~tasks:notifications +ping +xreadgroup +xack +xgroup
user vault on >${VAULT_PASS} ~tasks:vault_ops ~vault:lock:* +ping +xreadgroup +xack +xgroup +set +del
user bridge on >${BRIDGE_PASS} ~bridge:* +ping +get +set +hget +hset +hmget +hdel +del +sadd +srem +smembers +hgetall +keys
user controller on >${CONTROLLER_PASS} ~perms:* ~tasks:tool_results ~tasks:untrusted_calls +ping +hset +hget +hmget +del +xadd +xreadgroup +xack +xgroup
user app on >${APP_PASS} ~tasks:inbound ~tasks:vault_ops ~tasks:notifications +ping +xadd
EOF
    # 0640: owner read/write, group read-only, world no access.
    # Redis runs as GID 999; chgrp lets it read the file without world-readable exposure.
    chmod 640 config/redis.acl
    if [ "${PACKAGE_MANAGER}" == "apt" ]; then
        if ! sudo chgrp 999 config/redis.acl 2>/dev/null; then
            echo "❌ Cannot set GID 999 on config/redis.acl."
            echo "   Run manually: sudo chgrp 999 config/redis.acl"
            echo "   Redis will fail to start until this is fixed."
            exit 1
        fi
    fi

    # Append per-service URLs to .env (idempotent: skip if already present)
    if ! grep -q "GATEWAY_REDIS_URL" .env 2>/dev/null; then
        cat >> .env << EOF

# Per-service Redis credentials (generated by setup.sh generate_acl)
GATEWAY_REDIS_URL=redis://gateway:${GATEWAY_PASS}@localhost:6379
INFERENCE_REDIS_URL=redis://inference:${INFERENCE_PASS}@localhost:6379
RUNNER_REDIS_URL=redis://runner:${RUNNER_PASS}@localhost:6379
NOTIFICATION_REDIS_URL=redis://notification:${NOTIFICATION_PASS}@localhost:6379
VAULT_REDIS_URL=redis://vault:${VAULT_PASS}@localhost:6379
BRIDGE_REDIS_URL=redis://bridge:${BRIDGE_PASS}@localhost:6379
CONTROLLER_REDIS_URL=redis://controller:${CONTROLLER_PASS}@localhost:6379
APP_REDIS_URL=redis://app:${APP_PASS}@localhost:6379
EOF
    fi

    echo "✅ config/redis.acl created. .env updated with per-service Redis URLs."
}

# --- UFW + DOCKER-USER hardening (Linux only) ---
harden_firewall() {
    if [ "${PACKAGE_MANAGER}" != "apt" ]; then
        echo "ℹ️  Firewall hardening is Linux-only. Skipping on macOS."
        return
    fi

    if ! command -v ufw &> /dev/null; then
        echo "⚠️  ufw not found — install it with: sudo apt install ufw"
        return
    fi

    echo "--- Hardening firewall ---"

    # Set default-deny policy before enabling so no window exists with open policy
    sudo ufw default deny incoming
    sudo ufw default allow outgoing
    # Allow SSH so we don't lock ourselves out
    sudo ufw allow ssh
    sudo ufw --force enable

    # Docker bypasses UFW by writing iptables rules directly.
    # The DOCKER-USER chain is evaluated before Docker's own rules,
    # so rules here apply to all Docker-managed traffic.
    AFTER_RULES="/etc/ufw/after.rules"
    MARKER="# Belgrade OS DOCKER-USER rules"

    if grep -q "${MARKER}" "${AFTER_RULES}" 2>/dev/null; then
        echo "✅ DOCKER-USER rules already in ${AFTER_RULES}"
    else
        echo "Adding DOCKER-USER rules to ${AFTER_RULES}..."
        sudo tee -a "${AFTER_RULES}" > /dev/null << 'IPTABLES_EOF'

# Belgrade OS DOCKER-USER rules
# Block all external traffic from reaching Docker bridge networks directly.
# Only RELATED/ESTABLISHED connections (responses to outbound requests) are allowed.
*filter
:DOCKER-USER - [0:0]
-A DOCKER-USER -m state --state RELATED,ESTABLISHED -j ACCEPT
-A DOCKER-USER -i lo -j ACCEPT
-A DOCKER-USER -j DROP
COMMIT
IPTABLES_EOF
        sudo ufw reload
        echo "✅ DOCKER-USER rules applied and UFW reloaded."
    fi
}

# --- Generate .env ---
generate_env

# --- Generate Redis ACL ---
generate_acl

# --- Harden firewall ---
harden_firewall

echo "--- Checking System Prerequisites ---"
MISSING_DEPS=0
check_binary protoc || MISSING_DEPS=1
check_binary go || MISSING_DEPS=1
check_binary rustc || MISSING_DEPS=1
check_binary python3 || MISSING_DEPS=1
check_binary docker || MISSING_DEPS=1

if [ $MISSING_DEPS -eq 1 ]; then
    read -p "Some system dependencies are missing. Install them now? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        install_system_deps
    else
        echo "❌ Cannot proceed without system dependencies."
        exit 1
    fi
fi

# --- 3. Python Virtual Environment ---
echo "--- Setting up Python Virtual Environment ---"
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo "✅ Virtual environment created."
fi

source venv/bin/activate
pip install --upgrade pip

# --- 4. Belgrade OS Core Setup ---
echo "--- Installing Project Dependencies ---"
make deps

echo "--- Generating Protobuf Code ---"
make proto

echo "--- Building Binaries ---"
make build

# --- 5. Environment & Database ---
echo "--- Finalizing Setup ---"
# .env was already generated at startup via generate_env; no duplicate block needed.

mkdir -p vault logs apps data/postgres data/redis

echo ""
echo "🇷🇸 Belgrade OS is ready!"
echo "---------------------------------------------------------"
echo "1. Fill in CF_TUNNEL_TOKEN in .env"
echo "2. Seed permissions: python3 scripts/seed_permissions.py"
echo "3. Start everything: make start"
echo "4. Stop everything:  make stop"
echo "---------------------------------------------------------"
